In [1]:
from bs4 import BeautifulSoup
import requests

import pandas as pd
from pandas import Series,DataFrame

In [2]:
url = 'http://www.bbc.com/sport/football/tables'

In [3]:
result = requests.get(url)
c = result.content

In [4]:
soup = BeautifulSoup(c,"lxml")

In [5]:
summary = soup.find('div',{'class':'stats', 'id':'blq-content'})
tables = summary.find_all('table')

In [6]:
data = []

rows = tables[0].findAll('tr')

for tr in rows:
    cols = tr.findAll('td')
    
    for td in cols: 
        
        text = td.find(text=True)
        print text,
        data.append(text)

Last updated 1 hour ago None No movement Chelsea 26 20 3 3 55 19 36 63

None No movement Tottenham Hotspur 26 15 8 3 50 18 32 53

None No movement Liverpool 27 15 7 5 58 34 24 52

None No movement Manchester City 25 16 4 5 51 29 22 52

None No movement Arsenal 26 15 5 6 55 31 24 50

None No movement Manchester United 26 13 10 3 39 22 17 49

None No movement Everton 26 12 8 6 42 27 15 44

None No movement West Bromwich Albion 27 11 7 9 36 34 2 40

None No movement Stoke City 27 9 8 10 32 40 -8 35

None No movement Southampton 26 9 6 11 32 34 -2 33

None No movement West Ham United 26 9 6 11 35 44 -9 33

None No movement Burnley 27 9 4 14 30 40 -10 31

None No movement Watford 27 8 7 12 33 47 -14 31

None No movement Bournemouth 27 7 6 14 37 52 -15 27

None No movement Leicester City 27 7 6 14 30 45 -15 27

None No movement Swansea City 27 8 3 16 35 59 -24 27

None No movement Crystal Palace 27 7 4 16 35 46 -11 25

None No movement Middlesbrough 27 4 10 13 19 30 -11 22

None No movement Hull City 27 5 6 16 24 53 -29 21

None No movement Sunderland 26 5 4 17 24 48 -24 19

In [7]:
#Data scraped from the web
data

[u'\n',
 u'Last updated 1 hour ago',
 None,
 u'No movement',
 u'Chelsea',
 u'26',
 u'20',
 u'3',
 u'3',
 u'55',
 u'19',
 u'36',
 u'63',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Tottenham Hotspur',
 u'26',
 u'15',
 u'8',
 u'3',
 u'50',
 u'18',
 u'32',
 u'53',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Liverpool',
 u'27',
 u'15',
 u'7',
 u'5',
 u'58',
 u'34',
 u'24',
 u'52',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Manchester City',
 u'25',
 u'16',
 u'4',
 u'5',
 u'51',
 u'29',
 u'22',
 u'52',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Arsenal',
 u'26',
 u'15',
 u'5',
 u'6',
 u'55',
 u'31',
 u'24',
 u'50',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Manchester United',
 u'26',
 u'13',
 u'10',
 u'3',
 u'39',
 u'22',
 u'17',
 u'49',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Everton',
 u'26',
 u'12',
 u'8',
 u'6',
 u'42',
 u'27',
 u'15',
 u'44',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'West Bromwich Albion',
 u'27',
 u'11',
 u'7',
 u'9',
 u'36',
 u'34',
 u'2',
 u'40',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Stoke City',
 u'27',
 u'9',
 u'8',
 u'10',
 u'32',
 u'40',
 u'-8',
 u'35',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Southampton',
 u'26',
 u'9',
 u'6',
 u'11',
 u'32',
 u'34',
 u'-2',
 u'33',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'West Ham United',
 u'26',
 u'9',
 u'6',
 u'11',
 u'35',
 u'44',
 u'-9',
 u'33',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Burnley',
 u'27',
 u'9',
 u'4',
 u'14',
 u'30',
 u'40',
 u'-10',
 u'31',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Watford',
 u'27',
 u'8',
 u'7',
 u'12',
 u'33',
 u'47',
 u'-14',
 u'31',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Bournemouth',
 u'27',
 u'7',
 u'6',
 u'14',
 u'37',
 u'52',
 u'-15',
 u'27',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Leicester City',
 u'27',
 u'7',
 u'6',
 u'14',
 u'30',
 u'45',
 u'-15',
 u'27',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Swansea City',
 u'27',
 u'8',
 u'3',
 u'16',
 u'35',
 u'59',
 u'-24',
 u'27',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Crystal Palace',
 u'27',
 u'7',
 u'4',
 u'16',
 u'35',
 u'46',
 u'-11',
 u'25',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Middlesbrough',
 u'27',
 u'4',
 u'10',
 u'13',
 u'19',
 u'30',
 u'-11',
 u'22',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Hull City',
 u'27',
 u'5',
 u'6',
 u'16',
 u'24',
 u'53',
 u'-29',
 u'21',
 u'\n',
 u'\n',
 None,
 u'No movement',
 u'Sunderland',
 u'26',
 u'5',
 u'4',
 u'17',
 u'24',
 u'48',
 u'-24',
 u'19',
 u'\n',
 u'\n']

In [8]:
#Pulling the headers from the web table
headers = [th.getText() for th in
          soup.findAll('tr',limit=2)[0].findAll('th')]

In [9]:
headers

[u'',
 u'Position',
 u'Team',
 u'P',
 u'W',
 u'D',
 u'L',
 u'F',
 u'A',
 u'GD',
 u'Pts',
 u'Last 10 games results',
 u'Match status']

In [10]:
data_rows = soup.findAll('tr')[1:]
player_data = [[td.getText() for td in data_rows[i].findAll('td')]
              for i in range(len(data_rows))]

In [11]:
#Recreating web table as a panda data frame
df = pd.DataFrame(player_data, columns = headers)

In [12]:
df.head()

,,Position,Team,P,W,D,L,F,A,GD,Pts,Last 10 games results,Match status
0,\n,Last updated 1 hour ago,None,None,None,None,None,None,None,None,None,None,None
1,,No movement 1,Chelsea,26,20,3,3,55,19,36,63,\nWin\nWin\nWin\nLoss\nWin\nWin\nDraw\nWin\nDr...,\nReport of Chelsea's last match
2,,No movement 2,Tottenham Hotspur,26,15,8,3,50,18,32,53,\nWin\nWin\nWin\nWin\nWin\nDraw\nDraw\nWin\nLo...,\nReport of Tottenham Hotspur's last match
3,,No movement 3,Liverpool,27,15,7,5,58,34,24,52,\nWin\nWin\nDraw\nDraw\nLoss\nDraw\nLoss\nWin\...,\nReport of Liverpool's last match
4,,No movement 4,Manchester City,25,16,4,5,51,29,22,52,\nWin\nWin\nWin\nLoss\nWin\nLoss\nDraw\nWin\nW...,\nReport of Manchester City's last match

In [13]:
#Cleaning up the table
df.drop(['Position','Last 10 games results','Match status'],axis=1,inplace=True)
df.drop([0],inplace=True)

In [14]:
df

                      Team   P   W   D   L   F   A   GD Pts
1                  Chelsea  26  20   3   3  55  19   36  63
2        Tottenham Hotspur  26  15   8   3  50  18   32  53
3                Liverpool  27  15   7   5  58  34   24  52
4          Manchester City  25  16   4   5  51  29   22  52
5                  Arsenal  26  15   5   6  55  31   24  50
6        Manchester United  26  13  10   3  39  22   17  49
7                  Everton  26  12   8   6  42  27   15  44
8     West Bromwich Albion  27  11   7   9  36  34    2  40
9               Stoke City  27   9   8  10  32  40   -8  35
10             Southampton  26   9   6  11  32  34   -2  33
11         West Ham United  26   9   6  11  35  44   -9  33
12                 Burnley  27   9   4  14  30  40  -10  31
13                 Watford  27   8   7  12  33  47  -14  31
14             Bournemouth  27   7   6  14  37  52  -15  27
15          Leicester City  27   7   6  14  30  45  -15  27
16            Swansea City  27   8   3  16  35  59  -24  27
17          Crystal Palace  27   7   4  16  35  46  -11  25
18           Middlesbrough  27   4  10  13  19  30  -11  22
19               Hull City  27   5   6  16  24  53  -29  21
20              Sunderland  26   5   4  17  24  48  -24  19

In [15]:
# http://savvastjortjoglou.com/nba-draft-part01-scraping.html